
export const gallery = {
  name:"gallery",
  theme: "light",
  object: [
    {
      tag:"h1",
      txt:"Galeria"
    },
    {
      tag:"wrapper",
      itemWidth:30,
      items: [
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/1-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/2-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/3-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/4-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/6-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/7-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/8-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/9-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/10-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/11-1024x683.jpg"
        },
        {
          tag:"img",
          width:25,
          src:"https://autogaz.bzdrive.com/images/gallery/12-1024x683.jpg"
        }
      ]
    }
  ]
}